source: sfdc
target: sfdc_predictive_analytics

# Decide how many samples are used for training
# test_sample_rate = 1.0 - train_sample_rate
train_sample_rate: 0.8

# For training, positive samples will be over-sampled x-times
pos_oversampling: 3

# If true, generate title-category mapping table on your own data
# by using Python script;
# you need to make sure if Python environment exists on your local environment
generate_title_mapping: false
