in:
  type: gcs
  bucket: ${gcs.bucket}
  path_prefix: ${gcs.filepath}
  auth_method: json_key
  json_keyfile:
    content: "${secret:gcp.jsonkey}"
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ","
    quote: "\""
    escape: "\""
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: time, type: long}
    - {name: host, type: string}
    - {name: path, type: string}
    - {name: referer, type: string}
    - {name: code, type: long}
out: {mode: append}
exec: {}
filters: []
