in:
  type: shopify
  target: ${shopify.target}
  apikey: ${secret:shopify.apikey}
  password: ${secret:shopify.password}
  store_name: ${secret:shopify.store_name}
  from_date: "2020-01-09"
  fetch_days: 2
  incremental: "true"
out:
  mode: replace
exec: {}
filters:
- type: rename
  rules:
  - rule: upper_to_lower
  - rule: character_types
    pass_types: ["a-z", "0-9"]
    pass_characters: "_"
    replace: "_"
  - rule: first_character_types
    pass_types: ["a-z"]
    pass_characters: "_"
    prefix: "_"
  - rule: unique_number_suffix
    max_length: 128
- type: add_time
  to_column: {name: time}
  from_value: {mode: upload_time}
