# For more advanced config options, please check these URLs.
# @see https://docs.treasuredata.com/display/public/INT/MySQL+Import+Integration
# @see https://github.com/embulk/embulk-input-jdbc/tree/master/embulk-input-mysql
---
in:
  type: mysql
  host: ${secret:mysql.host}
  port: ${secret:mysql.port}
  user: ${secret:mysql.user}
  password: ${secret:mysql.password}
  database: source_db
  query: "select * from `source_table` limit 10"
out: {}
exec: {}
filters: []
