# For more advanced config options, please check these URLs.
# @see https://docs.treasuredata.com/display/public/INT/Amazon+S3+Import+Integration
# @see https://github.com/embulk/embulk-input-s3
---
in:
  type: s3
  access_key_id: ${secret:s3.access_key_id}
  secret_access_key: ${secret:s3.secret_access_key}
  bucket: ganesh-demo-jan
  path_prefix: ganesh
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    skip_header_lines: 1
    columns:
    - name: id
      type: long
    - name: company
      type: string
    - name: customer
      type: string
    - name: time
      type: long
out: {}
exec: {}
filters: []
